spring:
  datasource:
    url: jdbc:mysql://localhost:3308/ebrainsoft_study?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ebsoft
    password: ebsoft
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.connection.Entity # 추가하면 XML에서 패키지명 생략 가능
  configuration:
    map-underscore-to-camel-case: true